"""ANYfileIO-to-ANYsolver SESAM adapter integration tests."""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from anysolver.elements import ShellElement
from anysolver.sesam_fem import import_sesam_fem


def _work_dir() -> Path:
    path = Path(".pytest_tmp_sesam_fem") / str(os.getpid())
    path.mkdir(parents=True, exist_ok=True)
    return path


def _mixed_shell_fem() -> str:
    return "\n".join(
        [
            "IDENT          100               1",
            "DATE          2026              6              23",
            "        Generated by ANYsolver test",
            "UNITS            1               1               1",
            "MISOSEL          1  2.100000D+11  3.000000D-01  7.850000D+03",
            "TDMATER          1  S355 steel",
            "GELTH           10  2.000000D-02",
            "GCOORD           1               0               0               0",
            "GCOORD           2               1               0               0",
            "GCOORD           3               0               1               0",
            "GCOORD           4               1               1               0",
            "GNODE            1               1               6          123456",
            "GNODE            2               2               6          123456",
            "GNODE            3               3               6          123456",
            "GNODE            4               4               6          123456",
            "GELMNT1        100               0              25               0               1               2               3",
            "GELREF1        100               1              10",
            "GELMNT1        200               0              24               0               1               2               4               3",
            "GELREF1        200               1              10",
            "BNBCD            1               6               1               1               1               0               0               0",
            "FOOBAR          99",
            "IEND",
            "",
        ]
    )


def _transformed_shell_sif() -> str:
    return "\n".join(
        [
            "IDENT          101               1",
            "UNITS            1               1               1",
            "MISOSEL          1  2.100000D+11  3.000000D-01  7.850000D+03",
            "GELTH           10  2.000000D-02",
            "GUNIVEC          5               0               0               1",
            "BNTRCOS          7               1               0               0               0               1               0               0               0               1",
            "GCOORD           1               0               0               0",
            "GCOORD           2               1               0               0",
            "GCOORD           3               1               1               0",
            "GCOORD           4               0               1               0",
            "GELMNT1        100               0              24               0               1               2               3               4",
            "GELREF1        100               1               0               0               0               0               0               0              10               0               0               7",
            "RVSTRESS         1               0             100               0              24               0    1.000000E+08               0               0    1.000000E+08               0",
            "IEND",
            "",
        ]
    )


def _oriented_beam_fem() -> str:
    return "\n".join(
        [
            "IDENT          102               1",
            "UNITS            1               1               1",
            "MISOSEL          1  2.100000D+11  3.000000D-01  7.850000D+03",
            "GBEAMG           1               0    2.000000E-02    1.000000E-06    2.000000E-06    3.000000E-06",
            "GUNIVEC          5               0               0               1",
            "GCOORD           1               0               0               0",
            "GCOORD           2               1               0               0",
            "GELMNT1        300               0              15               0               1               2",
            "GELREF1        300               1               0               0               0               0               0               0               1               0               0               5",
            "IEND",
            "",
        ]
    )


def test_import_sesam_fem_builds_native_shell_model() -> None:
    path = _work_dir() / "import_shells.FEM"
    path.write_text(_mixed_shell_fem(), encoding="ascii")

    result = import_sesam_fem(path)

    assert result.model is not None
    assert result.model.mesh.num_nodes == 4
    assert result.model.mesh.num_elements == 2
    assert result.element_count_by_type == {25: 1, 24: 1}
    assert isinstance(result.model.mesh.elements[100], ShellElement)
    assert result.model.mesh.elements[100].thickness == pytest.approx(0.02)
    assert len(result.model.boundary_conditions) == 1


def test_fem_importer_attaches_explicit_shell_transform_metadata() -> None:
    path = _work_dir() / "transformed_shell.SIF"
    path.write_text(_transformed_shell_sif(), encoding="ascii")

    result = import_sesam_fem(path)
    shell = result.model.mesh.elements[100]

    assert getattr(shell, "sesam_transform_ids") == (7,)
    assert getattr(shell, "sesam_local_axes") == {
        "x": (1.0, 0.0, 0.0),
        "y": (0.0, 1.0, 0.0),
        "z": (0.0, 0.0, 1.0),
    }


def test_fem_importer_maps_gunivec_to_beam_orientation() -> None:
    path = _work_dir() / "oriented_beam.FEM"
    path.write_text(_oriented_beam_fem(), encoding="ascii")

    result = import_sesam_fem(path)
    beam = result.model.mesh.elements[300]

    assert getattr(beam, "sesam_transform_ids") == (5,)
    assert beam.cross_section["orientation"] == (0.0, 0.0, 1.0)
