"""ANYsolver beam/shell finite-element package.

The package provides native model/element/load objects, separate matrix
assembly, constrained and free-free linear solves, mass/modal and eigenvalue
buckling analysis, incremental geometric/material nonlinear statics,
corotational large-rotation response, current-area follower pressure, implicit
transient dynamics, limited rigid-sphere contact and engineering erosion,
generated-geometry/capacity workflows, material-history-aware result recovery,
and solver adapters over ANYfileio's SESAM/CalculiX interchange models.

All nodes use ``ux, uy, uz, rx, ry, rz`` in SI units. Supports and beam-shell
MPCs share the affine ``u = T q + u0`` reduction, and K/M/C/KG/F assembly stays
separate. Bounded arc-length continuation is available from the root API.

See the project README and ``docs/`` directory in the source repository for
the capability boundary, architecture, theory, and qualification evidence.
"""

from .fe_core import DOFManager, FEMesh, FEModel, Material, Node
from .control import (
    CancellationToken,
    ProgressCallback,
    ProgressEvent,
    SolveCancelled,
    cancellation_safe_point,
    emit_progress,
)
from .element_capabilities import ElementCapabilityError
from .algebraic_dynamics import AlgebraicDynamicsError
from .outcomes import (
    SolveDisposition,
    SolveOutcome,
    SupportsSolveOutcome,
    solve_outcome,
)
from .quantities import (
    QuantityUnavailableError,
    ReactionFrame,
    ResolvedResultQuantity,
    ResultQuantity,
    describe_result_quantities,
    registered_result_quantity_ids,
    resolve_result_quantity,
)
from .materials import (
    BeamMaterialProperties,
    ENGINEERING_VOIGT_ORDER,
    Hill48Yield,
    OrthotropicMaterial,
    StructuralMaterial,
    beam_material_properties,
    elastic_compliance_matrix,
    is_isotropic_material,
    is_orthotropic_material,
    material_symmetry,
    material_validation_errors,
    shell_characteristic_modulus,
    shell_material_matrices,
    validate_material,
)
from .sections import (
    GENERALIZED_BEAM_RESULTANT_ORDER,
    GENERALIZED_BEAM_STRAIN_ORDER,
    GENERALIZED_BEAM_VELOCITY_ORDER,
    SHELL_MEMBRANE_VOIGT_ORDER,
    SHELL_TRANSVERSE_SHEAR_ORDER,
    GeneralizedBeamSection,
    GeneralizedBeamSectionContract,
    GeneralizedShellSection,
    GeneralizedShellSectionProtocol,
    coerce_generalized_beam_section,
    coerce_generalized_shell_section,
    generalized_beam_mass_matrix,
    generalized_beam_stiffness,
    resolve_generalized_beam_section,
    validate_generalized_beam_section,
    validate_generalized_shell_section,
)
from .plasticity import (
    hill48_coefficients,
    hill48_equivalent_stress,
    hill48_plane_stress_coefficients,
    hill48_plane_stress_equivalent_stress,
    hill48_plane_stress_numerical_tangent,
    hill48_plane_stress_return_map,
)
from .elements import (
    DEFAULT_Q4_FORMULATION,
    DEFAULT_S3_FORMULATION,
    BeamElement,
    CoupledBeamShellElement,
    LEGACY_Q4_AVAILABLE_THROUGH,
    LEGACY_Q4_REMOVAL_TARGET,
    LegacyShellElement,
    LegacyQ4DeprecationWarning,
    LegacyS3MigrationWarning,
    QuadraticBeamElement,
    ShellElement,
    create_element,
    create_shell_element,
    shell_formulation_diagnostics,
    shell_element_from_dict,
)
from .e4_pl_element import (
    FORMULATION_ID as QUALIFIED_Q4_FORMULATION_ID,
    QualifiedE4PLShellElement,
)
from .e4_pl_s3_element import (
    FORMULATION_ID as QUALIFIED_S3_FORMULATION_ID,
    QualifiedE4PLS3ShellElement,
    QualifiedS3MigrationWarning,
)
from .e4_pl_s3_v2_element import (
    FORMULATION_ID as STRICT_FLAT_S3_V2_FORMULATION_ID,
    IMPLEMENTATION_ID as STRICT_FLAT_S3_V2_IMPLEMENTATION_ID,
    SELECTOR as STRICT_FLAT_S3_V2_SELECTOR,
    StrictFlatLinearCapabilityError,
    StrictFlatLinearE4PLS3V2ShellElement,
)
from .e4_pl_s3_v2b_element import (
    FORMULATION_ID as STRICT_FLAT_S3_V2B_FORMULATION_ID,
    IMPLEMENTATION_ID as STRICT_FLAT_S3_V2B_IMPLEMENTATION_ID,
    SELECTOR as STRICT_FLAT_S3_V2B_SELECTOR,
    StrictFlatLinearCapabilityError as StrictFlatLinearV2BCapabilityError,
    StrictFlatLinearE4PLS3V2BShellElement,
)
from .e4_pl_s3_v2c_element import (
    FORMULATION_ID as STRICT_FLAT_S3_V2C_FORMULATION_ID,
    IMPLEMENTATION_ID as STRICT_FLAT_S3_V2C_IMPLEMENTATION_ID,
    SELECTOR as STRICT_FLAT_S3_V2C_SELECTOR,
    StrictFlatLinearCapabilityError as StrictFlatLinearV2CCapabilityError,
    StrictFlatLinearE4PLS3V2CShellElement,
)
from .boundary import (
    BoundaryCondition,
    FixedSupport,
    InPlaneLoad,
    LoadCase,
    LoadCombination,
    PinnedSupport,
    RollerSupport,
    SymmetryBC,
)
from .cylinder_benchmarks import (
    CylinderBenchmarkConfig,
    CylinderBenchmarkResult,
    CylinderNominalStress,
    CylinderStressStatistics,
    build_cylindrical_shell_benchmark_model,
    nominal_cylinder_membrane_stress,
    run_cylindrical_shell_benchmark,
)
from .buckling import BucklingMode, BucklingResult, solve_eigenvalue_buckling
from .buckling_validity import (
    DEFAULT_BUCKLING_VALIDITY_PATH,
    generate_buckling_validity_report,
    write_buckling_validity_report,
)
from .nonlinear import NonlinearLimitPointResult, NonlinearLoadStep, solve_nonlinear_load_stepping
from .benchmarks import DEFAULT_BENCHMARK_PATH, run_infrastructure_benchmarks, write_benchmark_report
from .kernel_warmup import warm_fe_solver_kernels
from .beam_shell_verification import (
    DEFAULT_BEAM_SHELL_VERIFICATION_PATH,
    VerificationCase,
    VerificationCaseResult,
    run_beam_shell_verification,
    verification_manifest_cases,
    write_beam_shell_verification_report,
)
from .mesh_load_bc_verification import (
    DEFAULT_MESH_LOAD_BC_VERIFICATION_PATH,
    MeshLoadBCCase,
    MeshLoadBCCaseResult,
    mesh_load_bc_manifest_cases,
    mesh_load_bc_result_by_case,
    run_mesh_load_bc_verification,
    write_mesh_load_bc_verification_report,
)
from .production_readiness import (
    DEFAULT_PRODUCTION_READINESS_DIR,
    CapabilityEntry,
    build_capability_matrix,
    build_verification_scope_statement,
    scope_statement_markdown,
    write_production_readiness_artifacts,
)
from .beam_validity import (
    DEFAULT_BEAM_VALIDITY_PATH,
    corotational_axial_extension_metric,
    corotational_rigid_rotation_metric,
    generate_beam_validity_report,
    write_beam_validity_report,
)
from .capacity_workflow import (
    DEFAULT_CAPACITY_WORKFLOW_PATH,
    CapacityWorkflowConfig,
    CapacityWorkflowResult,
    MeshModeAdequacy,
    default_eigenmode_imperfection,
    evaluate_mode_mesh_adequacy,
    run_capacity_workflow_from_builder,
    run_nonlinear_capacity_workflow,
    write_capacity_workflow_report,
)
from .cases import (
    AnalysisCase,
    LoadCaseRef,
    PrestressCase,
    ResultCase,
    load_case_ref,
    load_signature_from_info,
    make_result_case,
    matrix_signature_from_info,
    solver_backend_from_info,
)
from .dynamics import (
    PressurePatch,
    TransientConfig,
    TransientResult,
    assemble_pressure_patch_load_vector,
    solve_transient_newmark,
)
from .contact import (
    NonlinearTransientConfig,
    RigidSphereImpact,
    SphereContactConfig,
    SphereContactRecord,
    SphereImpactResult,
    assemble_sphere_contact_load_vector,
    recommend_sphere_contact_penalty,
    solve_transient_sphere_impact,
    validate_contact_configuration,
)
from .fracture import (
    DeletedElementRecord,
    ElementDeletionConfig,
    FractureConfig,
    ImpactDamageConfig,
    ImpactFractureConfig,
    PlasticImpactDamageConfig,
)
from .element_qualification import (
    DEFAULT_ELEMENT_QUALIFICATION_PATH,
    beam_qualification_metrics,
    generate_element_qualification_report,
    q4_q8_convergence_cost_sweep,
    q8_free_mode_metric,
    q8_mass_metric,
    q8_patch_metric,
    q8r_free_mode_metric,
    q8r_hourglass_assessment,
    q8r_mass_metric,
    q8r_patch_metric,
    reference_q8_geometries,
    write_element_qualification_report,
)
from .external_references import (
    CALCULIX_EXECUTABLE_ENV,
    DEFAULT_CALCULIX_RUN_PATH,
    DEFAULT_EXTERNAL_REFERENCE_PATH,
    CalculixParsedResults,
    ExternalReferenceCase,
    calculix_solver_provenance,
    evaluate_calculix_comparisons,
    generate_external_reference_cases,
    generate_external_reference_report,
    merge_calculix_results,
    parse_calculix_dat,
    parse_calculix_frd,
    resolve_calculix_executable,
    run_calculix_reference_case,
    write_calculix_input_deck,
    write_external_reference_report,
)
from .plasticity_qualification import (
    DEFAULT_PLASTICITY_QUALIFICATION_PATH,
    algorithmic_tangent_path_metrics,
    algorithmic_tangent_performance_metrics,
    dnv_curve_metric,
    element_tangent_metrics,
    generate_plasticity_qualification_report,
    global_newton_tangent_benchmark_metrics,
    material_point_path_metrics,
    reference_plastic_curve,
    write_plasticity_qualification_report,
    yield_function_residual,
)
from .recovery import (
    MemoryEstimate,
    PatchRecoveryConfig,
    RecoveryExecutionReport,
    RecoveryConfig,
    ResourcePolicyError,
    ResourceConfig,
    StressRecoveryProvenance,
    StressRecoveryResult,
    clear_recovery_batch_plan,
    default_recovery_config,
    enforce_memory_limit,
    estimate_model_memory,
    filter_reactions,
    recover_element_stresses,
    recover_element_stresses_with_report,
    recover_shell_patch_stresses,
    recover_stress_result,
    recovery_metadata,
    select_node_displacements,
)
from .recovery_policy import (
    DEFAULT_RECOVERY_POLICY_PATH,
    generate_recovery_policy_report,
    write_recovery_policy_report,
)
from .material_curves import (
    DNVC208MaterialCurve,
    FiberSectionPlasticityConfig,
    curve_from_properties,
    dnv_c208_steel_properties,
    dnv_c208_steel_curve,
)
from .imperfections import (
    CompositeImperfection,
    EigenmodeImperfection,
    ImperfectionCalibrationResult,
    ImperfectionField,
    StandardImperfection,
    apply_imperfection,
    calibrate_imperfection_amplitude,
    imperfection_from_buckling_mode,
    standard_flange_twist,
    standard_member_bow,
    standard_plate_mode,
)
from .nonlinear_static import (
    BeamInitialField,
    DisplacementControl,
    NonlinearConvergenceSettings,
    NonlinearLoadProgram,
    NonlinearLoadStage,
    NonlinearStaticResult,
    NonlinearStaticStep,
    NonlinearIncrementSnapshot,
    ShellInitialField,
    solve_static_nonlinear,
)
from .arc_length import ArcLengthControl, ArcLengthResult, ArcLengthStep, solve_static_arc_length
from .anystructure_fem_mode import (
    AnyStructureFEMConfig,
    AnyStructureFEMResult,
    GeneratedGeometryFEMConfig,
    GeneratedGeometryFEMResult,
    build_fe_model_from_generated_geometry,
    build_symmetric_load_case,
    idealize_generated_geometry_members,
    recover_prestress_from_static_result,
    run_anystructure_fem_mode,
    run_generated_geometry_fem,
)
from .matrix_assembly import (
    AssemblyError,
    assemble_damping_matrix,
    assemble_external_load_system,
    assemble_external_load_tangent,
    assemble_geometric_stiffness_matrix,
    assemble_load_matrix,
    assemble_load_vector,
    assemble_mass_matrix,
    assemble_stiffness_matrix,
    assemble_system,
)
from .assembly import (
    build_constraint_transformation,
    compute_constraint_force_diagnostics,
    reconstruct_full_solution,
    solve_linear,
    solve_linear_many,
    solve_nonlinear,
)
from .analysis_session import (
    AnalysisSession,
    ConstraintPlan,
    OutputSelectionPlan,
    StructuralMatrixPlan,
)
from .linalg import (
    AutoSparseSolverBackend,
    FactorizationCache,
    FactorizationHandle,
    MatrixClass,
    SparseSolverBackend,
    cached_inverse_operator,
    factorize,
    factorize_cached,
    solve_many,
    sparse_matrix_signature,
)
from .mass_properties import MassProperties, calculate_mass_properties, element_mass_points
from .modal import ModalMode, ModalResult, solve_free_vibration
from .mesh_gen import (
    InterpolatedBeamShellMPCElement,
    MeshConfig,
    PanelGeometry,
    StiffenerCrossSection,
    generate_beam_mesh,
    generate_simple_panel_mesh,
    generate_stiffened_panel_mesh,
    verify_mesh_quality,
)
from .results import (
    DisplacementResult,
    FEResult,
    StressResult,
    compare_with_analytical,
    create_fe_result,
    post_process_results,
    recover_nodal_stresses,
)
from .constraint_audit import (
    ConstraintEquation,
    ConstraintAuditIssue,
    ConstraintAuditReport,
    audit_constraints,
    constraint_residual_summary,
)
from .validation import (
    LoadResultant,
    ProductionValidationIssue,
    ProductionValidationReport,
    ShellPatchSummary,
    dof_order_signature,
    load_case_resultant,
    load_vector_resultant,
    max_abs,
    mpc_constraint_residuals,
    nullspace_diagnostics,
    shell_element_patch_summary,
    validate_production_model,
)
from .reference_cases import (
    CalculixReferenceCase,
    ShellConvergencePoint,
    ShellConvergenceTable,
    classify_reference_case_from_nodes,
    discover_calculix_reference_cases,
    discover_calculix_shell_convergence_tables,
    parse_calculix_shell_convergence_file,
    summarize_inp_geometry,
    upstream_calculix_reference_manifest,
    upstream_calculix_shell_reference_values,
)
from .shell_benchmarks import (
    ShellBenchmarkComparison,
    ShellBenchmarkComparisonPoint,
    ShellBenchmarkResult,
    compare_shell_benchmark_to_reference,
    run_simple_supported_shell_benchmark,
    run_simple_supported_shell_convergence,
    shell_benchmark_results_to_convergence_table,
    write_internal_shell_convergence_table,
)
from .s4_validity import (
    DEFAULT_S4_VALIDITY_PATH,
    bending_patch_metric,
    free_element_mode_metric,
    generate_s4_validity_report,
    membrane_patch_metric,
    reference_s4_geometries,
    s4_s8_comparison,
    shear_patch_metric,
    thin_plate_locking_sweep,
    write_s4_validity_report,
)
from .sesam_fem import (
    FemRawRecord,
    SesamFemDocument,
    SesamFemError,
    SesamFemExportReport,
    SesamFemImportResult,
    export_sesam_fem,
    import_sesam_fem,
    read_raw_records,
    read_sesam_fem_document,
    validate_sesam_fem_document,
    write_sesam_fem_document,
)

__version__ = "0.3.1"

__all__ = [
    # Core classes
    "DOFManager",
    "FEMesh",
    "FEModel",
    "Hill48Yield",
    "Material",
    "Node",
    "CancellationToken",
    "ProgressCallback",
    "ProgressEvent",
    "SolveCancelled",
    "cancellation_safe_point",
    "emit_progress",
    "SolveDisposition",
    "SolveOutcome",
    "SupportsSolveOutcome",
    "solve_outcome",
    "QuantityUnavailableError",
    "ReactionFrame",
    "ResolvedResultQuantity",
    "ResultQuantity",
    "describe_result_quantities",
    "registered_result_quantity_ids",
    "resolve_result_quantity",
    "OrthotropicMaterial",
    "StructuralMaterial",
    "BeamMaterialProperties",
    "ENGINEERING_VOIGT_ORDER",
    "beam_material_properties",
    "elastic_compliance_matrix",
    "is_isotropic_material",
    "is_orthotropic_material",
    "material_symmetry",
    "material_validation_errors",
    "shell_characteristic_modulus",
    "shell_material_matrices",
    "validate_material",
    "GENERALIZED_BEAM_RESULTANT_ORDER",
    "GENERALIZED_BEAM_STRAIN_ORDER",
    "GENERALIZED_BEAM_VELOCITY_ORDER",
    "SHELL_MEMBRANE_VOIGT_ORDER",
    "SHELL_TRANSVERSE_SHEAR_ORDER",
    "GeneralizedBeamSection",
    "GeneralizedBeamSectionContract",
    "GeneralizedShellSection",
    "GeneralizedShellSectionProtocol",
    "coerce_generalized_beam_section",
    "coerce_generalized_shell_section",
    "generalized_beam_mass_matrix",
    "generalized_beam_stiffness",
    "resolve_generalized_beam_section",
    "validate_generalized_beam_section",
    "validate_generalized_shell_section",
    "hill48_coefficients",
    "hill48_equivalent_stress",
    "hill48_plane_stress_coefficients",
    "hill48_plane_stress_equivalent_stress",
    "hill48_plane_stress_numerical_tangent",
    "hill48_plane_stress_return_map",
    # Elements
    "BeamElement",
    "CoupledBeamShellElement",
    "DEFAULT_Q4_FORMULATION",
    "DEFAULT_S3_FORMULATION",
    "LEGACY_Q4_AVAILABLE_THROUGH",
    "LEGACY_Q4_REMOVAL_TARGET",
    "LegacyShellElement",
    "LegacyQ4DeprecationWarning",
    "LegacyS3MigrationWarning",
    "QuadraticBeamElement",
    "QualifiedE4PLShellElement",
    "QualifiedE4PLS3ShellElement",
    "QualifiedS3MigrationWarning",
    "QUALIFIED_Q4_FORMULATION_ID",
    "QUALIFIED_S3_FORMULATION_ID",
    "STRICT_FLAT_S3_V2_FORMULATION_ID",
    "STRICT_FLAT_S3_V2_IMPLEMENTATION_ID",
    "STRICT_FLAT_S3_V2_SELECTOR",
    "ShellElement",
    "StrictFlatLinearCapabilityError",
    "StrictFlatLinearE4PLS3V2ShellElement",
    "create_element",
    "create_shell_element",
    "shell_formulation_diagnostics",
    "shell_element_from_dict",
    # Boundary and loads
    "BoundaryCondition",
    "FixedSupport",
    "InPlaneLoad",
    "LoadCase",
    "LoadCombination",
    "PinnedSupport",
    "RollerSupport",
    "SymmetryBC",
    # Cylinder benchmarks
    "CylinderBenchmarkConfig",
    "CylinderBenchmarkResult",
    "CylinderNominalStress",
    "CylinderStressStatistics",
    "build_cylindrical_shell_benchmark_model",
    "nominal_cylinder_membrane_stress",
    "run_cylindrical_shell_benchmark",
    # Buckling
    "BucklingMode",
    "BucklingResult",
    "solve_eigenvalue_buckling",
    "DEFAULT_BUCKLING_VALIDITY_PATH",
    "generate_buckling_validity_report",
    "write_buckling_validity_report",
    # Nonlinear stability
    "NonlinearLimitPointResult",
    "NonlinearLoadStep",
    "solve_nonlinear_load_stepping",
    # Case/provenance model
    "AnalysisCase",
    "LoadCaseRef",
    "PrestressCase",
    "ResultCase",
    "load_case_ref",
    "load_signature_from_info",
    "make_result_case",
    "matrix_signature_from_info",
    "solver_backend_from_info",
    "DEFAULT_BENCHMARK_PATH",
    "run_infrastructure_benchmarks",
    "write_benchmark_report",
    "warm_fe_solver_kernels",
    "DEFAULT_BEAM_SHELL_VERIFICATION_PATH",
    "VerificationCase",
    "VerificationCaseResult",
    "run_beam_shell_verification",
    "verification_manifest_cases",
    "write_beam_shell_verification_report",
    "DEFAULT_MESH_LOAD_BC_VERIFICATION_PATH",
    "MeshLoadBCCase",
    "MeshLoadBCCaseResult",
    "mesh_load_bc_manifest_cases",
    "mesh_load_bc_result_by_case",
    "run_mesh_load_bc_verification",
    "write_mesh_load_bc_verification_report",
    "DEFAULT_PRODUCTION_READINESS_DIR",
    "CapabilityEntry",
    "build_capability_matrix",
    "build_verification_scope_statement",
    "scope_statement_markdown",
    "write_production_readiness_artifacts",
    "DEFAULT_BEAM_VALIDITY_PATH",
    "corotational_axial_extension_metric",
    "corotational_rigid_rotation_metric",
    "generate_beam_validity_report",
    "write_beam_validity_report",
    "DEFAULT_CAPACITY_WORKFLOW_PATH",
    "CapacityWorkflowConfig",
    "CapacityWorkflowResult",
    "MeshModeAdequacy",
    "default_eigenmode_imperfection",
    "evaluate_mode_mesh_adequacy",
    "run_capacity_workflow_from_builder",
    "run_nonlinear_capacity_workflow",
    "write_capacity_workflow_report",
    # Linear transient dynamics / slamming v1
    "PressurePatch",
    "TransientConfig",
    "TransientResult",
    "ElementCapabilityError",
    "AlgebraicDynamicsError",
    "assemble_pressure_patch_load_vector",
    "solve_transient_newmark",
    "NonlinearTransientConfig",
    "RigidSphereImpact",
    "SphereContactConfig",
    "SphereContactRecord",
    "SphereImpactResult",
    "assemble_sphere_contact_load_vector",
    "recommend_sphere_contact_penalty",
    "solve_transient_sphere_impact",
    "validate_contact_configuration",
    "DeletedElementRecord",
    "ElementDeletionConfig",
    "FractureConfig",
    "ImpactDamageConfig",
    "ImpactFractureConfig",
    "PlasticImpactDamageConfig",
    "DEFAULT_ELEMENT_QUALIFICATION_PATH",
    "beam_qualification_metrics",
    "generate_element_qualification_report",
    "q4_q8_convergence_cost_sweep",
    "q8_free_mode_metric",
    "q8_mass_metric",
    "q8_patch_metric",
    "q8r_free_mode_metric",
    "q8r_hourglass_assessment",
    "q8r_mass_metric",
    "q8r_patch_metric",
    "reference_q8_geometries",
    "write_element_qualification_report",
    "CALCULIX_EXECUTABLE_ENV",
    "DEFAULT_CALCULIX_RUN_PATH",
    "DEFAULT_EXTERNAL_REFERENCE_PATH",
    "CalculixParsedResults",
    "ExternalReferenceCase",
    "calculix_solver_provenance",
    "evaluate_calculix_comparisons",
    "generate_external_reference_cases",
    "generate_external_reference_report",
    "merge_calculix_results",
    "parse_calculix_dat",
    "parse_calculix_frd",
    "resolve_calculix_executable",
    "run_calculix_reference_case",
    "write_calculix_input_deck",
    "write_external_reference_report",
    "DEFAULT_PLASTICITY_QUALIFICATION_PATH",
    "algorithmic_tangent_path_metrics",
    "algorithmic_tangent_performance_metrics",
    "dnv_curve_metric",
    "element_tangent_metrics",
    "generate_plasticity_qualification_report",
    "global_newton_tangent_benchmark_metrics",
    "material_point_path_metrics",
    "reference_plastic_curve",
    "write_plasticity_qualification_report",
    "yield_function_residual",
    "MemoryEstimate",
    "PatchRecoveryConfig",
    "RecoveryExecutionReport",
    "RecoveryConfig",
    "ResourcePolicyError",
    "ResourceConfig",
    "StressRecoveryProvenance",
    "StressRecoveryResult",
    "clear_recovery_batch_plan",
    "default_recovery_config",
    "enforce_memory_limit",
    "estimate_model_memory",
    "filter_reactions",
    "recover_element_stresses",
    "recover_element_stresses_with_report",
    "recover_shell_patch_stresses",
    "recover_stress_result",
    "recovery_metadata",
    "select_node_displacements",
    "DEFAULT_RECOVERY_POLICY_PATH",
    "generate_recovery_policy_report",
    "write_recovery_policy_report",
    # Incremental geometric/material nonlinear statics
    "DNVC208MaterialCurve",
    "FiberSectionPlasticityConfig",
    "curve_from_properties",
    "dnv_c208_steel_properties",
    "dnv_c208_steel_curve",
    "CompositeImperfection",
    "EigenmodeImperfection",
    "ImperfectionCalibrationResult",
    "ImperfectionField",
    "StandardImperfection",
    "apply_imperfection",
    "calibrate_imperfection_amplitude",
    "imperfection_from_buckling_mode",
    "standard_flange_twist",
    "standard_member_bow",
    "standard_plate_mode",
    "BeamInitialField",
    "DisplacementControl",
    "NonlinearConvergenceSettings",
    "NonlinearLoadProgram",
    "NonlinearLoadStage",
    "NonlinearStaticResult",
    "NonlinearStaticStep",
    "NonlinearIncrementSnapshot",
    "ShellInitialField",
    "solve_static_nonlinear",
    "ArcLengthControl",
    "ArcLengthResult",
    "ArcLengthStep",
    "solve_static_arc_length",
    # Generated-geometry FEM mode
    "AnyStructureFEMConfig",
    "AnyStructureFEMResult",
    "GeneratedGeometryFEMConfig",
    "GeneratedGeometryFEMResult",
    "build_fe_model_from_generated_geometry",
    "build_symmetric_load_case",
    "idealize_generated_geometry_members",
    "recover_prestress_from_static_result",
    "run_anystructure_fem_mode",
    "run_generated_geometry_fem",
    # Assembly and solving
    "AnalysisSession",
    "ConstraintPlan",
    "OutputSelectionPlan",
    "StructuralMatrixPlan",
    "AssemblyError",
    "assemble_damping_matrix",
    "assemble_external_load_system",
    "assemble_external_load_tangent",
    "assemble_geometric_stiffness_matrix",
    "assemble_load_matrix",
    "assemble_load_vector",
    "assemble_mass_matrix",
    "assemble_stiffness_matrix",
    "assemble_system",
    "build_constraint_transformation",
    "compute_constraint_force_diagnostics",
    "reconstruct_full_solution",
    "solve_linear",
    "solve_linear_many",
    "solve_nonlinear",
    "MatrixClass",
    "AutoSparseSolverBackend",
    "SparseSolverBackend",
    "FactorizationCache",
    "FactorizationHandle",
    "cached_inverse_operator",
    "factorize",
    "factorize_cached",
    "solve_many",
    "sparse_matrix_signature",
    "MassProperties",
    "calculate_mass_properties",
    "element_mass_points",
    "ModalMode",
    "ModalResult",
    "solve_free_vibration",
    # Mesh generation
    "InterpolatedBeamShellMPCElement",
    "MeshConfig",
    "PanelGeometry",
    "StiffenerCrossSection",
    "generate_beam_mesh",
    "generate_simple_panel_mesh",
    "generate_stiffened_panel_mesh",
    "verify_mesh_quality",
    # Results
    "DisplacementResult",
    "FEResult",
    "StressResult",
    "compare_with_analytical",
    "create_fe_result",
    "post_process_results",
    "recover_nodal_stresses",
    # Constraint integrity
    "ConstraintAuditIssue",
    "ConstraintEquation",
    "ConstraintAuditReport",
    "audit_constraints",
    "constraint_residual_summary",
    # Validation helpers
    "LoadResultant",
    "ProductionValidationIssue",
    "ProductionValidationReport",
    "ShellPatchSummary",
    "dof_order_signature",
    "load_case_resultant",
    "load_vector_resultant",
    "max_abs",
    "mpc_constraint_residuals",
    "nullspace_diagnostics",
    "shell_element_patch_summary",
    "validate_production_model",
    # Reference cases
    "CalculixReferenceCase",
    "ShellConvergencePoint",
    "ShellConvergenceTable",
    "classify_reference_case_from_nodes",
    "discover_calculix_reference_cases",
    "discover_calculix_shell_convergence_tables",
    "parse_calculix_shell_convergence_file",
    "summarize_inp_geometry",
    "upstream_calculix_reference_manifest",
    "upstream_calculix_shell_reference_values",
    # Shell benchmarks
    "ShellBenchmarkComparison",
    "ShellBenchmarkComparisonPoint",
    "ShellBenchmarkResult",
    "compare_shell_benchmark_to_reference",
    "run_simple_supported_shell_benchmark",
    "run_simple_supported_shell_convergence",
    "shell_benchmark_results_to_convergence_table",
    "write_internal_shell_convergence_table",
    # S4 validity
    "DEFAULT_S4_VALIDITY_PATH",
    "bending_patch_metric",
    "free_element_mode_metric",
    "generate_s4_validity_report",
    "membrane_patch_metric",
    "reference_s4_geometries",
    "s4_s8_comparison",
    "shear_patch_metric",
    "thin_plate_locking_sweep",
    "write_s4_validity_report",
    # SESAM compatibility facade and solver-model adapters (syntax: ANYfileio)
    "FemRawRecord",
    "SesamFemDocument",
    "SesamFemError",
    "SesamFemExportReport",
    "SesamFemImportResult",
    "export_sesam_fem",
    "import_sesam_fem",
    "read_raw_records",
    "read_sesam_fem_document",
    "validate_sesam_fem_document",
    "write_sesam_fem_document",
]

# Stable-ID, array-based progressive damage and hard-deletion lifecycle.
from .activity import (
    ActivityChange,
    ActivityFilter,
    ActivityPolicy,
    ContributionPolicy,
    CouplingPolicy,
    CouplingResolution,
    CouplingResolutionError,
    DamageHistoryEntry,
    ElementActivity,
    ElementActivityError,
    ElementActivityManager,
    ElementActivityPolicies,
    ElementActivityPolicy,
    OrphanDofReport,
    RestartStateError,
)

__all__ += [
    "ActivityChange",
    "ActivityFilter",
    "ActivityPolicy",
    "ContributionPolicy",
    "CouplingPolicy",
    "CouplingResolution",
    "CouplingResolutionError",
    "DamageHistoryEntry",
    "ElementActivity",
    "ElementActivityError",
    "ElementActivityManager",
    "ElementActivityPolicies",
    "ElementActivityPolicy",
    "OrphanDofReport",
    "RestartStateError",
]
